myweb/mainpage/urls.py
from django.urls import path, include
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
]

myweb/myweb/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainpage/', include("mainpage.urls")),
    path('', views.index, name='index'),
]

myweb/mainpage/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AccRegNum(models.Model):
    account_id = models.PositiveIntegerField(primary_key=True)
    key = models.CharField(max_length=32)
    index = models.PositiveIntegerField()
    value = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'acc_reg_num'
        unique_together = (('account_id', 'key', 'index'),)


class AccRegStr(models.Model):
    account_id = models.PositiveIntegerField(primary_key=True)
    key = models.CharField(max_length=32)
    index = models.PositiveIntegerField()
    value = models.CharField(max_length=254)

    class Meta:
        managed = False
        db_table = 'acc_reg_str'
        unique_together = (('account_id', 'key', 'index'),)


class Achievement(models.Model):
    char_id = models.PositiveIntegerField(primary_key=True)
    id = models.BigIntegerField()
    count1 = models.PositiveIntegerField()
    count2 = models.PositiveIntegerField()
    count3 = models.PositiveIntegerField()
    count4 = models.PositiveIntegerField()
    count5 = models.PositiveIntegerField()
    count6 = models.PositiveIntegerField()
    count7 = models.PositiveIntegerField()
    count8 = models.PositiveIntegerField()
    count9 = models.PositiveIntegerField()
    count10 = models.PositiveIntegerField()
    completed = models.DateTimeField(blank=True, null=True)
    rewarded = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'achievement'
        unique_together = (('char_id', 'id'),)


class Atcommandlog(models.Model):
    atcommand_id = models.AutoField(primary_key=True)
    atcommand_date = models.DateTimeField()
    account_id = models.PositiveIntegerField()
    char_id = models.PositiveIntegerField()
    char_name = models.CharField(max_length=25)
    map = models.CharField(max_length=11)
    command = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'atcommandlog'


class Auction(models.Model):
    auction_id = models.BigAutoField(primary_key=True)
    seller_id = models.PositiveIntegerField()
    seller_name = models.CharField(max_length=30)
    buyer_id = models.PositiveIntegerField()
    buyer_name = models.CharField(max_length=30)
    price = models.PositiveIntegerField()
    buynow = models.PositiveIntegerField()
    hours = models.SmallIntegerField()
    timestamp = models.PositiveIntegerField()
    nameid = models.PositiveSmallIntegerField()
    item_name = models.CharField(max_length=50)
    type = models.SmallIntegerField()
    refine = models.PositiveIntegerField()
    attribute = models.PositiveIntegerField()
    card0 = models.PositiveSmallIntegerField()
    card1 = models.PositiveSmallIntegerField()
    card2 = models.PositiveSmallIntegerField()
    card3 = models.PositiveSmallIntegerField()
    option_id0 = models.SmallIntegerField()
    option_val0 = models.SmallIntegerField()
    option_parm0 = models.IntegerField()
    option_id1 = models.SmallIntegerField()
    option_val1 = models.SmallIntegerField()
    option_parm1 = models.IntegerField()
    option_id2 = models.SmallIntegerField()
    option_val2 = models.SmallIntegerField()
    option_parm2 = models.IntegerField()
    option_id3 = models.SmallIntegerField()
    option_val3 = models.SmallIntegerField()
    option_parm3 = models.IntegerField()
    option_id4 = models.SmallIntegerField()
    option_val4 = models.SmallIntegerField()
    option_parm4 = models.IntegerField()
    unique_id = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = 'auction'


class BonusScript(models.Model):
    char_id = models.PositiveIntegerField()
    script = models.TextField()
    tick = models.BigIntegerField()
    flag = models.PositiveSmallIntegerField()
    type = models.PositiveIntegerField()
    icon = models.SmallIntegerField()

    class Meta:
        managed = False
        db_table = 'bonus_script'


class Branchlog(models.Model):
    branch_id = models.AutoField(primary_key=True)
    branch_date = models.DateTimeField()
    account_id = models.IntegerField()
    char_id = models.IntegerField()
    char_name = models.CharField(max_length=25)
    map = models.CharField(max_length=11)

    class Meta:
        managed = False
        db_table = 'branchlog'


class BuyingstoreItems(models.Model):
    buyingstore_id = models.PositiveIntegerField()
    index = models.PositiveSmallIntegerField()
    item_id = models.PositiveIntegerField()
    amount = models.PositiveSmallIntegerField()
    price = models.PositiveIntegerField()

    class Meta:
        managed = False
        db_table = 'buyingstore_items'


class Buyingstores(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    account_id = models.PositiveIntegerField()
    char_id = models.PositiveIntegerField()
    sex = models.CharField(max_length=1)
    map = models.CharField(max_length=20)
    x = models.PositiveSmallIntegerField()
    y = models.PositiveSmallIntegerField()
    title = models.CharField(max_length=80)
    limit = models.PositiveIntegerField()
    body_direction = models.CharField(max_length=1)
    head_direction = models.CharField(max_length=1)
    sit = models.CharField(max_length=1)
    autotrade = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'buyingstores'


class CartInventory(models.Model):
    char_id = models.IntegerField()
    nameid = models.PositiveSmallIntegerField()
    amount = models.IntegerField()
    equip = models.PositiveIntegerField()
    identify = models.SmallIntegerField()
    refine = models.PositiveIntegerField()
    attribute = models.IntegerField()
    card0 = models.PositiveSmallIntegerField()
    card1 = models.PositiveSmallIntegerField()
    card2 = models.PositiveSmallIntegerField()
    card3 = models.PositiveSmallIntegerField()
    option_id0 = models.SmallIntegerField()
    option_val0 = models.SmallIntegerField()
    option_parm0 = models.IntegerField()
    option_id1 = models.SmallIntegerField()
    option_val1 = models.SmallIntegerField()
    option_parm1 = models.IntegerField()
    option_id2 = models.SmallIntegerField()
    option_val2 = models.SmallIntegerField()
    option_parm2 = models.IntegerField()
    option_id3 = models.SmallIntegerField()
    option_val3 = models.SmallIntegerField()
    option_parm3 = models.IntegerField()
    option_id4 = models.SmallIntegerField()
    option_val4 = models.SmallIntegerField()
    option_parm4 = models.IntegerField()
    expire_time = models.PositiveIntegerField()
    bound = models.PositiveIntegerField()
    unique_id = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = 'cart_inventory'


class Cashlog(models.Model):
    time = models.DateTimeField()
    char_id = models.IntegerField()
    type = models.CharField(max_length=1)
    cash_type = models.CharField(max_length=1)
    amount = models.IntegerField()
    map = models.CharField(max_length=11)

    class Meta:
        managed = False
        db_table = 'cashlog'


class Char(models.Model):
    char_id = models.AutoField(primary_key=True)
    account_id = models.PositiveIntegerField()
    char_num = models.IntegerField()
    name = models.CharField(unique=True, max_length=30)
    class_field = models.PositiveSmallIntegerField(db_column='class')  # Field renamed because it was a Python reserved word.
    base_level = models.PositiveSmallIntegerField()
    job_level = models.PositiveSmallIntegerField()
    base_exp = models.BigIntegerField()
    job_exp = models.BigIntegerField()
    zeny = models.PositiveIntegerField()
    str = models.PositiveSmallIntegerField()
    agi = models.PositiveSmallIntegerField()
    vit = models.PositiveSmallIntegerField()
    int = models.PositiveSmallIntegerField()
    dex = models.PositiveSmallIntegerField()
    luk = models.PositiveSmallIntegerField()
    max_hp = models.PositiveIntegerField()
    hp = models.PositiveIntegerField()
    max_sp = models.PositiveIntegerField()
    sp = models.PositiveIntegerField()
    status_point = models.PositiveIntegerField()
    skill_point = models.PositiveIntegerField()
    option = models.IntegerField()
    karma = models.IntegerField()
    manner = models.SmallIntegerField()
    party_id = models.PositiveIntegerField()
    guild_id = models.PositiveIntegerField()
    pet_id = models.PositiveIntegerField()
    homun_id = models.PositiveIntegerField()
    elemental_id = models.PositiveIntegerField()
    hair = models.PositiveIntegerField()
    hair_color = models.PositiveSmallIntegerField()
    clothes_color = models.PositiveSmallIntegerField()
    body = models.PositiveSmallIntegerField()
    weapon = models.PositiveSmallIntegerField()
    shield = models.PositiveSmallIntegerField()
    head_top = models.PositiveSmallIntegerField()
    head_mid = models.PositiveSmallIntegerField()
    head_bottom = models.PositiveSmallIntegerField()
    robe = models.PositiveSmallIntegerField()
    last_map = models.CharField(max_length=11)
    last_x = models.PositiveSmallIntegerField()
    last_y = models.PositiveSmallIntegerField()
    save_map = models.CharField(max_length=11)
    save_x = models.PositiveSmallIntegerField()
    save_y = models.PositiveSmallIntegerField()
    partner_id = models.PositiveIntegerField()
    online = models.IntegerField()
    father = models.PositiveIntegerField()
    mother = models.PositiveIntegerField()
    child = models.PositiveIntegerField()
    fame = models.PositiveIntegerField()

myweb/mainpage/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.hashers import make_password, check_password
from .models import Login
from django.contrib.auth.models import User
from datetime import datetime

class SignupForm(forms.ModelForm):
    password_confirm = forms.CharField(widget=forms.PasswordInput,
                                       help_text="Re-enter your password.")

    class Meta:
        model = Login
        fields = ('userid', 'user_pass', 'password_confirm', 'sex', 'email',)

        labels = {
            'username': _('Username'),
            'email': _('Email address *'),
            'user_pass': _('Password'),
            'password_confirm': _('Password confirmation'),
        }
        widgets = {
            'password': forms.PasswordInput,
            'password_confirm': forms.PasswordInput,
            'email_address': forms.EmailInput,
        }
        help_texts = {
            # 'username': _('Username may only contain alphanumeric characters\
            #               or single hyphens,and cannot begin or end with a hy\
            #               phen.'),
            # 'password': _("Make sure it's more than 15 characters OR at least\
            #               8 characters including a number and a lowercase let\
            #               ter."),
            # 'password_confirm': _("Re-enter your password.",)
        }
        error_messages = {
            'username': {
                'max_length': _("This username is too long."),
            },
        }

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get('user_pass')
        password_confirm = cleaned_data.get('password_confirm')
        if not check_password(password_confirm, password):
            raise forms.ValidationError(
                'Password and confirmation password does not match.'
            )
        username_list = list(Login.objects.values_list('userid', flat=True))
        username = cleaned_data.get('userid')
        if username in username_list:
            raise forms.ValidationError(
                'This name has exist, please choose another name.'
            )

    def clean_password(self):
        encrypt_password = make_password(self.cleaned_data['user_pass'])
        if encrypt_password:
            return encrypt_password
        else:
            raise forms.ValidationError(
                'Password encryption fail, please choose another password'
            )

myweb/mainpage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from .forms import SignupForm

# Create your views here.
def mainpage(request):
    """Signup view"""
    if request.method == 'POST':
        # Get signup form from template
        form = SignupForm(request.POST)
        if form.is_valid():
            # Valid form then save
            form.save()
            # return render(request, 'mainpage/signup_success.html')
            return HttpResponse("Sign up success.")
        else:
            return render(request, 'mainpage/mainpage.html', {'form': form,})
    else:
        # Send signup form to template
        form = SignupForm()
    return render(request, 'mainpage/mainpage.html', {'form': form})

def signup(request):
    """Signup view"""
    if request.method == 'POST':
        # Get signup form from template
        form = SignupForm(request.POST)
        if form.is_valid():
            # Valid form then save
            form.save()
            # return render(request, 'mainpage/signup_success.html')
            return HttpResponse("Sign up success.")
        else:
            return render(request, 'mainpage/mainpage.html', {'form': form,})
    else:
        # Send signup form to template
        form = SignupForm()
    return render(request, 'mainpage/mainpage.html', {'form': form})

myweb/mainpage/templates/mainpage/base.html
<!doctype html>
<html lang="en">

<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Self CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'mainpage/css/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Latte Ragnarok Online</title>
</head>

<body>
    {% block mainpage %}
    {% endblock %}
    <!-- {% block login %}
    {% endblock %}
    {% block signup %}
    {% endblock %}
    {% block signup_success %}
    {% endblock %}

    {% block movies %}
    {% endblock %}
    {% block add_movie %}
    {% endblock %}
    {% block movie_detail %}
    {% endblock %}

    {% block actors %}
    {% endblock %}
    {% block add_actor %}
    {% endblock %}
    {% block actor_detail %}
    {% endblock %}

    {% block awards %}
    {% endblock %}
    {% block add_award %}
    {% endblock %}
    {% block award_detail %}
    {% endblock %} -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

myweb/mainpage/templates/mainpage/mainpage.html
{% extends 'mainpage/base.html' %}

{% block mainpage %}
{% load static %}

<nav class="nowrap navbar navbar-light sticky-top" style="background-color: #e3f2fd;">
    <a href="#"><img src="{% static "mainpage/images/home_logo.jpg" %}" class="home__logo" /></a>
    <a class="navbar-brand navbar-brand__font" href="#">Trang chủ</a>
    <a class="navbar-brand" href="#">Tải game</a>
    <a class="navbar-brand" href="#">Đăng ký</a>
    <a class="navbar-brand" href="#">Thông tin</a>
    <a class="navbar-brand" href="#">Hỗ trợ</a>
    <a class="navbar-brand" href="#">Tin tức</a>
    <a class="navbar-brand" href="#">Diễn đàn</a>
    <a class="navbar-brand" href="#">Wiki</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent">
      <span class="navbar-toggler-icon"></span>
    </button>
</nav>

<div style="display: flex; flex-flow: column wrap;">
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
    <a style="font-size: 50px;">asdasdasdasdsadadasdsadsadsadsadadsdasdsadsadasdadasdadasds</a>
</div>

{% endblock %}

myweb/mainpage/templates/mainpage/signup.html
{% extends 'mainpage/base.html' %}

{% block signup %}
{% load static %}
<div class="container">
</br>
<h1>Create your account:</h1>
</br>
<form action="{% url "mainpage:mainpage" %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group row">
        <label for="id_username" class="col-sm-2 col-form-label">Username:</label>
        <div class="col-sm-7">
            <input type="text" class="form-control" id="id_username" name="username" placeholder="Username">
        </div>
    </div>

    {{ form.password.errors }}
    <div class="form-group row">
        <label for="id_password" class="col-sm-2 col-form-label">Password:</label>
        <div class="col-sm-7">
            <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
        </div>
    </div>

    {{ form.password_confirm.errors }}
    <div class="form-group row">
        <label for="id_password_confirm" class="col-sm-2 col-form-label">Password confirmation:</label>
        <div class="col-sm-7">
            <input type="password" class="form-control" id="id_password_confirm" name="password_confirm" placeholder="Password confirmation">
        </div>
    </div>
    </br>
    <input type="submit" class="btn btn-success" value="Signup">
    <a class="btn btn-link" href="{% url "mainpage:mainpage" %}">Homepage</a>
</form>
</div>
{% endblock %}